name: Scanning
on:
  pull_request:
    branches:
      - '**'
  schedule:
    - cron: '0 4 * * 4' # Every Thursday at 04:00
  workflow_dispatch:

jobs:
  scan:
    uses: hmcts/secrets-scanner/.github/workflows/secret-scanning.yml@add-system-ids-rule
    secrets: inherit